# Generated by Django 3.0.3 on 2020-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terme',
            name='importe',
            field=models.CharField(max_length=1),
        ),
    ]
